package frc.robot.configuration;

public enum CANDevice {
	
	SWERVE_FRONT_LEFT_DRIVE_MOTOR_CONTROLLER(1),
	
	SWERVE_FRONT_LEFT_STEER_MOTOR_CONTROLLER(2),
	
	SWERVE_FRONT_RIGHT_DRIVE_MOTOR_CONTROLLER(3),
	
	SWERVE_FRONT_RIGHT_STEER_MOTOR_CONTROLLER(4),
	
	SWERVE_REAR_LEFT_DRIVE_MOTOR_CONTROLLER(5),
	
	SWERVE_REAR_LEFT_STEER_MOTOR_CONTROLLER(6),
	
	SWERVE_REAR_RIGHT_DRIVE_MOTOR_CONTROLLER(7),
	
	SWERVE_REAR_RIGHT_STEER_MOTOR_CONTROLLER(8),
	
	ELEVATOR_MOTOR_CONTROLLER(10),
	
	MAILBOX_MOTOR_CONTROLLER(11),
	
	AGITATOR_MOTOR_CONTROLLER(12),
	
	CLIMBER_WINCH_MOTOR_CONTROLLER(13),
	
	ALGAE_MANIPULATOR_MOTOR_CONTROLLER(14),
	
	INTAKE_UPPER_LASER_CAN(20),
	
	INTAKE_LOWER_LASER_CAN(21);
	
	public final int id;
	
	CANDevice(int id) {
		
		this.id = id;
		
	}
	
}
